version: '1.0'

networks:
  app:
    driver: bridge

services:
  postgres:
    image: postgres:16.0
    container_name: link_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=link
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
        - app

  link-shortener:
    build: .
    ports:
      - 8090:8090
    depends_on:
      - postgres
    networks:
      - app